sharingan:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/sharingan?useSSL=false&useUnicode=true&useAffectedRows=true&serverTimezone=Asia/Shanghai
    username: root
    password: root
  maven:
    registry: http://127.0.0.1:8081
    username:
    password:
  rpc:
    dubbo:
      registry: zookeeper://127.0.0.1:2181
      username:
      password:
    sofa:
      registry: zookeeper://127.0.0.1:2181
      direct-url: bolt://127.0.0.1:12200
    springcloud:
      registry: http://127.0.0.1:8761/eureka